# Generated by Django 6.0.3 on 2026-03-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_address_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_type',
            field=models.CharField(default='initials', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_seed',
            field=models.CharField(default='', max_length=50),
        ),
    ]
