# Generated by Django 6.0.3 on 2026-03-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_avatar_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_seed',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
