# Generated by Django 6.0.3 on 2026-03-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_avatar_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
