# Generated by Django 6.0.5 on 2026-05-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stationreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='eta',
            field=models.CharField(blank=True, default='15–25 min', max_length=50),
        ),
    ]
